name: Auto Generate Sitemap

on:
  schedule:
    - cron: '0 5 * * *'  # Daily at 5am UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Sitemap Generator
      run: npm install -g sitemap-generator-cli

    - name: Generate Sitemap
      run: |
        mkdir -p public
        sitemap-generator https://la.curations.cc \
          --filepath ./public/sitemap.xml \
          --maxDepth 2 \
          --stripQuerystring true

    - name: Commit sitemap.xml
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add public/sitemap.xml
        git commit -m "Auto update sitemap"
        git push
