name: Auto Generate Sitemap

on:
  schedule:
    - cron: '0 5 * * *'  # daily at 5am UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install sitemap-generator-cli
      run: npm install -g sitemap-generator-cli

    - name: Generate sitemap.xml at root
      run: |
        sitemap-generator https://la.curations.cc --filepath ./sitemap.xml --maxDepth 2 --stripQuerystring true

    - name: Commit and push sitemap.xml if changed
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        if git diff --quiet; then
          echo "No changes to commit"
        else
          git add sitemap.xml
          git commit -m "Auto update sitemap"
          git push
        fi
